spring:
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/suggest_come_out?useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
debug: true